<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Membera.Shared.Messaging\Membera.Shared.Messaging.csproj" />
    <ProjectReference Include="..\..\Auth\Membera.Auth.Application\Membera.Auth.Application.csproj" />
    <ProjectReference Include="..\Membera.Merchant.Application\Membera.Merchant.Application.csproj" />
  </ItemGroup>

</Project>
