version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: membera-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: membera_auth
    ports:
      - "5432:5432"
    volumes:
      - membera-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: membera-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: membera-redis
    ports:
      - "6379:6379"

volumes:
  membera-postgres-data: